# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oscilla.ui'
#
# Created: Wed Oct 31 11:56:52 2018
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OscillaWindow(object):
    def setupUi(self, OscillaWindow):
        OscillaWindow.setObjectName(_fromUtf8("OscillaWindow"))
        OscillaWindow.resize(891, 569)
        self.centralwidget = QtGui.QWidget(OscillaWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.hloAll = QtGui.QHBoxLayout()
        self.hloAll.setObjectName(_fromUtf8("hloAll"))
        self.vloControls = QtGui.QVBoxLayout()
        self.vloControls.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.vloControls.setObjectName(_fromUtf8("vloControls"))
        self.cbDrivers = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbDrivers.sizePolicy().hasHeightForWidth())
        self.cbDrivers.setSizePolicy(sizePolicy)
        self.cbDrivers.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cbDrivers.setObjectName(_fromUtf8("cbDrivers"))
        self.vloControls.addWidget(self.cbDrivers)
        self.cbSignals = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSignals.sizePolicy().hasHeightForWidth())
        self.cbSignals.setSizePolicy(sizePolicy)
        self.cbSignals.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cbSignals.setObjectName(_fromUtf8("cbSignals"))
        self.vloControls.addWidget(self.cbSignals)
        self.hloAxes = QtGui.QHBoxLayout()
        self.hloAxes.setObjectName(_fromUtf8("hloAxes"))
        self.labelAxis = QtGui.QLabel(self.centralwidget)
        self.labelAxis.setObjectName(_fromUtf8("labelAxis"))
        self.hloAxes.addWidget(self.labelAxis)
        self.rbAxis1 = QtGui.QRadioButton(self.centralwidget)
        self.rbAxis1.setObjectName(_fromUtf8("rbAxis1"))
        self.hloAxes.addWidget(self.rbAxis1)
        self.rbAxis2 = QtGui.QRadioButton(self.centralwidget)
        self.rbAxis2.setObjectName(_fromUtf8("rbAxis2"))
        self.hloAxes.addWidget(self.rbAxis2)
        self.rbAxis3 = QtGui.QRadioButton(self.centralwidget)
        self.rbAxis3.setObjectName(_fromUtf8("rbAxis3"))
        self.hloAxes.addWidget(self.rbAxis3)
        self.vloControls.addLayout(self.hloAxes)
        self.btnAdd = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.vloControls.addWidget(self.btnAdd)
        self.btnRemove = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemove.sizePolicy().hasHeightForWidth())
        self.btnRemove.setSizePolicy(sizePolicy)
        self.btnRemove.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        self.vloControls.addWidget(self.btnRemove)
        self.lvActiveSig = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvActiveSig.sizePolicy().hasHeightForWidth())
        self.lvActiveSig.setSizePolicy(sizePolicy)
        self.lvActiveSig.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lvActiveSig.setObjectName(_fromUtf8("lvActiveSig"))
        self.vloControls.addWidget(self.lvActiveSig)
        self.hloClearButtons = QtGui.QHBoxLayout()
        self.hloClearButtons.setContentsMargins(-1, 0, -1, 0)
        self.hloClearButtons.setObjectName(_fromUtf8("hloClearButtons"))
        self.btnClearSignal = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClearSignal.sizePolicy().hasHeightForWidth())
        self.btnClearSignal.setSizePolicy(sizePolicy)
        self.btnClearSignal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnClearSignal.setObjectName(_fromUtf8("btnClearSignal"))
        self.hloClearButtons.addWidget(self.btnClearSignal)
        self.btnClearAll = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClearAll.sizePolicy().hasHeightForWidth())
        self.btnClearAll.setSizePolicy(sizePolicy)
        self.btnClearAll.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnClearAll.setObjectName(_fromUtf8("btnClearAll"))
        self.hloClearButtons.addWidget(self.btnClearAll)
        self.vloControls.addLayout(self.hloClearButtons)
        self.btnShift = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShift.sizePolicy().hasHeightForWidth())
        self.btnShift.setSizePolicy(sizePolicy)
        self.btnShift.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnShift.setObjectName(_fromUtf8("btnShift"))
        self.vloControls.addWidget(self.btnShift)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vloControls.addItem(spacerItem)
        self.btnCLoop = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCLoop.sizePolicy().hasHeightForWidth())
        self.btnCLoop.setSizePolicy(sizePolicy)
        self.btnCLoop.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnCLoop.setPalette(palette)
        self.btnCLoop.setObjectName(_fromUtf8("btnCLoop"))
        self.vloControls.addWidget(self.btnCLoop)
        self.btnCurrents = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCurrents.sizePolicy().hasHeightForWidth())
        self.btnCurrents.setSizePolicy(sizePolicy)
        self.btnCurrents.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnCurrents.setPalette(palette)
        self.btnCurrents.setObjectName(_fromUtf8("btnCurrents"))
        self.vloControls.addWidget(self.btnCurrents)
        self.btnTarget = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTarget.sizePolicy().hasHeightForWidth())
        self.btnTarget.setSizePolicy(sizePolicy)
        self.btnTarget.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnTarget.setPalette(palette)
        self.btnTarget.setObjectName(_fromUtf8("btnTarget"))
        self.vloControls.addWidget(self.btnTarget)
        self.hloAll.addLayout(self.vloControls)
        self.vloCurves = QtGui.QVBoxLayout()
        self.vloCurves.setObjectName(_fromUtf8("vloCurves"))
        self.hloCurveButtons = QtGui.QHBoxLayout()
        self.hloCurveButtons.setObjectName(_fromUtf8("hloCurveButtons"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hloCurveButtons.addItem(spacerItem1)
        self.btnPause = QtGui.QPushButton(self.centralwidget)
        self.btnPause.setObjectName(_fromUtf8("btnPause"))
        self.hloCurveButtons.addWidget(self.btnPause)
        self.btnNow = QtGui.QPushButton(self.centralwidget)
        self.btnNow.setObjectName(_fromUtf8("btnNow"))
        self.hloCurveButtons.addWidget(self.btnNow)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hloCurveButtons.addItem(spacerItem2)
        self.vloCurves.addLayout(self.hloCurveButtons)
        self.hloAll.addLayout(self.vloCurves)
        self.gridLayout.addLayout(self.hloAll, 0, 0, 1, 1)
        OscillaWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(OscillaWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 891, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        OscillaWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OscillaWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        OscillaWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OscillaWindow)
        QtCore.QMetaObject.connectSlotsByName(OscillaWindow)

    def retranslateUi(self, OscillaWindow):
        OscillaWindow.setWindowTitle(_translate("OscillaWindow", "Dummy Window Title", None))
        self.labelAxis.setText(_translate("OscillaWindow", "Axis:", None))
        self.rbAxis1.setText(_translate("OscillaWindow", "1", None))
        self.rbAxis2.setText(_translate("OscillaWindow", "2", None))
        self.rbAxis3.setText(_translate("OscillaWindow", "3", None))
        self.btnAdd.setText(_translate("OscillaWindow", "Add Signal", None))
        self.btnRemove.setText(_translate("OscillaWindow", "Remove Selected", None))
        self.btnClearSignal.setText(_translate("OscillaWindow", "Clear Sel", None))
        self.btnClearAll.setText(_translate("OscillaWindow", "Clear All", None))
        self.btnShift.setText(_translate("OscillaWindow", "Shift Axis", None))
        self.btnCLoop.setText(_translate("OscillaWindow", "* Closed Loop *", None))
        self.btnCurrents.setText(_translate("OscillaWindow", "* Currents *", None))
        self.btnTarget.setText(_translate("OscillaWindow", "* Target *", None))
        self.btnPause.setText(_translate("OscillaWindow", "Pause", None))
        self.btnNow.setText(_translate("OscillaWindow", "Goto Now", None))

